services:
  - type: web
    name: iot-intrusion
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ids_project.wsgi:application"
